### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-html-meta-elements-_f2DoK#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://katie-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the respective validators should return no errors)

**Comment by chrisvfritz** [comment]
![So meta](http://s2.quickmeme.com/img/11/112719c33c3a4698176435e6ea2914b2547614339725a7f396081e48a50eefec.jpg)

💥  :shipit: 💥
